title: Reflexiones sobre Álgebra   # your title
author: Fernando Iván Danko # your name
description: Resoluciones, ejercicios, proyecciones y reflexiones sobre contenidos relacionados a la materia Álgebra II 61.08 / 81.08 de FIUBA 
avatar: /images/avatar.png # change avatar

# Build Settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 10
paginate_path: "/page:num/"
plugins: [jekyll-paginate]

# Comments
#disqus:
#  shortname: fernandoivndanko   # your disqus shortname

# Google Analytics
# google_analytics: xx-xxxxxxxx-1  # your google analytics
