title: Reflexiones sobre Álgebra   # your title
author: Fernando Danko # your name
description: Acá voy poniendo cosas piolas # your description
avatar: /images/avatar.png # change avatar

# Build Settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/page:num/"
plugins: [jekyll-paginate]

# Comments
#disqus:
#  shortname: fernandoivndanko   # your disqus shortname

# Google Analytics
# google_analytics: xx-xxxxxxxx-1  # your google analytics
